"""add unique constraint

Revision ID: 7f0b238457ee
Revises: acaa370cb12b
Create Date: 2023-02-21 01:11:10.233318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0b238457ee'
down_revision = 'acaa370cb12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_plant', ['temperature_sensor_pin', 'heating_element_pin', 'led_red_pin', 'led_green_pin', 'led_blue_pin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_constraint('unique_plant', type_='unique')

    # ### end Alembic commands ###
