"""initial migration

Revision ID: acaa370cb12b
Revises: 
Create Date: 2023-02-21 01:00:56.183011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acaa370cb12b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('wavelength', sa.Integer(), nullable=False),
    sa.Column('brightness', sa.Integer(), nullable=False),
    sa.Column('temperature_sensor_pin', sa.Integer(), nullable=False),
    sa.Column('heating_element_pin', sa.Integer(), nullable=False),
    sa.Column('led_red_pin', sa.Integer(), nullable=False),
    sa.Column('led_green_pin', sa.Integer(), nullable=False),
    sa.Column('led_blue_pin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heating_element_pin'),
    sa.UniqueConstraint('led_blue_pin'),
    sa.UniqueConstraint('led_green_pin'),
    sa.UniqueConstraint('led_red_pin'),
    sa.UniqueConstraint('temperature_sensor_pin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
