"""initial migration

Revision ID: fd6c61d61052
Revises: 
Create Date: 2023-03-15 13:05:37.110610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6c61d61052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('wavelength', sa.Integer(), nullable=False),
    sa.Column('brightness', sa.Integer(), nullable=False),
    sa.Column('temperature_sensor_pin', sa.Integer(), nullable=False),
    sa.Column('heating_element_pin', sa.Integer(), nullable=False),
    sa.Column('led_pin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heating_element_pin'),
    sa.UniqueConstraint('led_pin'),
    sa.UniqueConstraint('temperature_sensor_pin'),
    sa.UniqueConstraint('temperature_sensor_pin', 'heating_element_pin', name='unique_plant')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
